languageCode = "en"
languageName = "English"
weight = 1
title = "Matheus Pereira"

[params]
  displayName = "English"
  isoCode = "en-us"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "AI Developer"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Matheus Pereira"
#   image = "img/blowfish_logo.png"
  headline = "AI Developer"
#   bio = "A little bit about you"
  links = [
    { github = "https://github.com/matheper" },
    { linkedin = "https://linkedin.com/in/matheper" },
  ]
